// @ts-nocheck
import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue
} from '@/components/ui/select';
import {
  Tabs, TabsContent, TabsList, TabsTrigger
} from '@/components/ui/tabs';
import { toast } from 'sonner';
import {
  Loader2, Smartphone, Search, Ban, CheckCircle2, ShieldCheck, ShieldX, Activity, Plus,
  UserPlus, Gift, Link2Off, RefreshCw
} from 'lucide-react';
import AdminAssignNFCModal from './AdminAssignNFCModal';

const DEST_LABELS: Record<string, string> = {
  profile: 'Profile',
  review: 'Review',
  projects: 'Projects',
  custom: 'Custom URL',
};

export default function AdminNFCManagement() {
  const [tags, setTags] = useState<any[]>([]);
  const [businesses, setBusinesses] = useState<Record<string, any>>({});
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [bulkOpen, setBulkOpen] = useState(false);
  const [bulkCount, setBulkCount] = useState(10);
  const [bulkLabel, setBulkLabel] = useState('Bulk batch');
  const [assignOpen, setAssignOpen] = useState(false);
  const [assignMode, setAssignMode] = useState<'generate' | 'assign'>('generate');
  const [assignTagId, setAssignTagId] = useState<string | null>(null);

  const fetchData = async () => {
    setLoading(true);
    const { data: tagsData, error } = await supabase.from('nfc_tags')
      .select('*')
      .order('created_at', { ascending: false });
    if (error) { toast.error('Failed to load tags'); setLoading(false); return; }
    setTags(tagsData || []);

    const bizIds = [...new Set((tagsData || []).map(t => t.business_id).filter(Boolean))];
    if (bizIds.length) {
      const { data: bizData } = await supabase.from('business_profiles')
        .select('id, company_name, logo_url')
        .in('id', bizIds);
      const map: Record<string, any> = {};
      (bizData || []).forEach(b => { map[b.id] = b; });
      setBusinesses(map);
    }
    setLoading(false);
  };

  useEffect(() => { fetchData(); }, []);

  const filtered = useMemo(() => {
    return tags.filter(t => {
      if (statusFilter === 'pending' && t.approval_status !== 'pending_approval') return false;
      if (statusFilter === 'blocked' && !t.is_blocked) return false;
      if (statusFilter === 'active' && (!t.is_active || t.is_blocked)) return false;
      if (statusFilter === 'unassigned' && t.business_id) return false;
      if (search) {
        const s = search.toLowerCase();
        const biz = businesses[t.business_id]?.company_name?.toLowerCase() || '';
        if (!t.tag_code.toLowerCase().includes(s) &&
            !(t.label || '').toLowerCase().includes(s) &&
            !biz.includes(s)) return false;
      }
      return true;
    });
  }, [tags, search, statusFilter, businesses]);

  const blockToggle = async (tag: any) => {
    const { error } = await supabase.from('nfc_tags')
      .update({ is_blocked: !tag.is_blocked }).eq('id', tag.id);
    if (error) toast.error('Failed'); else { toast.success(tag.is_blocked ? 'Unblocked' : 'Blocked'); fetchData(); }
  };

  const approveCustom = async (tag: any, approve: boolean) => {
    const { error } = await supabase.from('nfc_tags')
      .update({ approval_status: approve ? 'approved' : 'rejected' }).eq('id', tag.id);
    if (error) toast.error('Failed'); else { toast.success(approve ? 'Approved' : 'Rejected'); fetchData(); }
  };

  const bulkGenerate = async () => {
    const count = Math.min(Math.max(parseInt(String(bulkCount), 10) || 0, 1), 100);
    const rows = Array.from({ length: count }, (_, i) => ({
      label: `${bulkLabel} #${i + 1}`,
      destination_type: 'profile',
      // tag_code auto-generated by trigger; business_id null = unassigned
    }));
    const { error } = await supabase.from('nfc_tags').insert(rows);
    if (error) toast.error('Failed: ' + error.message);
    else { toast.success(`${count} tags pre-generated`); setBulkOpen(false); fetchData(); }
  };

  const openAssign = (tagId: string) => {
    setAssignMode('assign'); setAssignTagId(tagId); setAssignOpen(true);
  };
  const openGenerateForBusiness = () => {
    setAssignMode('generate'); setAssignTagId(null); setAssignOpen(true);
  };
  const unassign = async (tag: any) => {
    if (!confirm(`Unassign tag "${tag.tag_code}" from its business?`)) return;
    const { error } = await supabase.from('nfc_tags')
      .update({ business_id: null, user_id: null, issued_by_admin: null })
      .eq('id', tag.id);
    if (error) toast.error('Failed: ' + error.message);
    else { toast.success('Unassigned — back in pool'); fetchData(); }
  };

  const stats = useMemo(() => ({
    total: tags.length,
    active: tags.filter(t => t.is_active && !t.is_blocked && t.approval_status === 'approved').length,
    pending: tags.filter(t => t.approval_status === 'pending_approval').length,
    blocked: tags.filter(t => t.is_blocked).length,
    totalTaps: tags.reduce((s, t) => s + (t.tap_count || 0), 0),
    unassigned: tags.filter(t => !t.business_id).length,
    issued: tags.filter(t => t.issued_by_admin).length,
  }), [tags]);

  const topBusinesses = useMemo(() => {
    const counts: Record<string, number> = {};
    tags.forEach(t => { if (t.business_id) counts[t.business_id] = (counts[t.business_id] || 0) + 1; });
    return Object.entries(counts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5)
      .map(([id, n]) => ({ id, count: n, name: businesses[id]?.company_name || 'Unknown' }));
  }, [tags, businesses]);

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <Smartphone className="w-6 h-6 text-primary" /> NFC Management
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Manage all NFC tags platform-wide. Block abusive tags and approve custom URLs.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button variant="outline" onClick={() => setBulkOpen(true)}>
            <Plus className="w-4 h-4 me-2" /> Bulk Pre-generate
          </Button>
          <Button onClick={openGenerateForBusiness}>
            <Gift className="w-4 h-4 me-2" /> Generate for Business
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
        <Card><CardContent className="p-4">
          <div className="text-xs text-muted-foreground">Total</div>
          <div className="text-xl font-bold mt-1">{stats.total}</div>
        </CardContent></Card>
        <Card><CardContent className="p-4">
          <div className="text-xs text-muted-foreground">Active</div>
          <div className="text-xl font-bold mt-1 text-green-600">{stats.active}</div>
        </CardContent></Card>
        <Card><CardContent className="p-4">
          <div className="text-xs text-muted-foreground">Pending</div>
          <div className="text-xl font-bold mt-1 text-yellow-600">{stats.pending}</div>
        </CardContent></Card>
        <Card><CardContent className="p-4">
          <div className="text-xs text-muted-foreground">Blocked</div>
          <div className="text-xl font-bold mt-1 text-destructive">{stats.blocked}</div>
        </CardContent></Card>
        <Card><CardContent className="p-4">
          <div className="text-xs text-muted-foreground">Total Taps</div>
          <div className="text-xl font-bold mt-1 flex items-center gap-1">
            <Activity className="w-4 h-4 text-primary" />{stats.totalTaps}
          </div>
        </CardContent></Card>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        <Card><CardContent className="p-4">
          <div className="text-xs text-muted-foreground">Unassigned pool</div>
          <div className="text-xl font-bold mt-1">{stats.unassigned}</div>
        </CardContent></Card>
        <Card><CardContent className="p-4">
          <div className="text-xs text-muted-foreground">Issued by R8ESTATE</div>
          <div className="text-xl font-bold mt-1 flex items-center gap-1">
            <Gift className="w-4 h-4 text-primary" />{stats.issued}
          </div>
        </CardContent></Card>
        <Card><CardContent className="p-4">
          <div className="text-xs text-muted-foreground mb-2">Top businesses by tags</div>
          {topBusinesses.length === 0 ? (
            <div className="text-xs text-muted-foreground">No assignments yet.</div>
          ) : (
            <ul className="space-y-1 text-sm">
              {topBusinesses.map(b => (
                <li key={b.id} className="flex items-center justify-between gap-2">
                  <span className="truncate">{b.name}</span>
                  <Badge variant="outline">{b.count}</Badge>
                </li>
              ))}
            </ul>
          )}
        </CardContent></Card>
      </div>

      <Tabs value={statusFilter} onValueChange={setStatusFilter}>
        <TabsList className="flex-wrap h-auto">
          <TabsTrigger value="all">All</TabsTrigger>
          <TabsTrigger value="pending">Pending Approval ({stats.pending})</TabsTrigger>
          <TabsTrigger value="active">Active</TabsTrigger>
          <TabsTrigger value="blocked">Blocked</TabsTrigger>
          <TabsTrigger value="unassigned">Unassigned (Bulk)</TabsTrigger>
        </TabsList>

        <TabsContent value={statusFilter} className="mt-4">
          <div className="relative mb-4">
            <Search className="w-4 h-4 absolute start-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
            <Input placeholder="Search by tag code, label, or business…"
              className="ps-9" value={search} onChange={e => setSearch(e.target.value)} />
          </div>

          {loading ? (
            <div className="flex justify-center py-12"><Loader2 className="w-6 h-6 animate-spin text-primary" /></div>
          ) : filtered.length === 0 ? (
            <Card><CardContent className="p-12 text-center text-muted-foreground">No tags match.</CardContent></Card>
          ) : (
            <div className="space-y-2">
              {filtered.map(tag => {
                const biz = businesses[tag.business_id];
                return (
                  <Card key={tag.id}>
                    <CardContent className="p-4">
                      <div className="flex flex-col md:flex-row md:items-center gap-3">
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 flex-wrap">
                            <code className="text-xs bg-muted px-2 py-1 rounded font-mono">{tag.tag_code}</code>
                            <span className="font-medium truncate">{tag.label}</span>
                            <Badge variant="outline">{DEST_LABELS[tag.destination_type]}</Badge>
                            {tag.is_blocked && <Badge variant="destructive">Blocked</Badge>}
                            {!tag.is_active && !tag.is_blocked && <Badge variant="outline">Paused</Badge>}
                            {tag.approval_status === 'pending_approval' && (
                              <Badge className="bg-yellow-500/10 text-yellow-700 border-yellow-300">Pending</Badge>
                            )}
                            {tag.approval_status === 'rejected' && <Badge variant="destructive">Rejected</Badge>}
                          </div>
                          <div className="text-xs text-muted-foreground mt-1">
                            {biz ? <>Business: <span className="font-medium">{biz.company_name}</span></> :
                              tag.business_id ? 'Business deleted' : 'Unassigned'}
                            <span className="mx-2">•</span>
                            <Activity className="w-3 h-3 inline" /> {tag.tap_count} taps
                            {tag.destination_type === 'custom' && tag.custom_url && (
                              <div className="mt-1 break-all">URL: {tag.custom_url}</div>
                            )}
                          </div>
                        </div>
                        <div className="flex flex-wrap items-center gap-2">
                          {tag.approval_status === 'pending_approval' && (
                            <>
                              <Button size="sm" variant="default" onClick={() => approveCustom(tag, true)}>
                                <ShieldCheck className="w-3 h-3 me-1" /> Approve
                              </Button>
                              <Button size="sm" variant="destructive" onClick={() => approveCustom(tag, false)}>
                                <ShieldX className="w-3 h-3 me-1" /> Reject
                              </Button>
                            </>
                          )}
                          <Button size="sm" variant={tag.is_blocked ? 'outline' : 'destructive'} onClick={() => blockToggle(tag)}>
                            {tag.is_blocked ? <><CheckCircle2 className="w-3 h-3 me-1" /> Unblock</> : <><Ban className="w-3 h-3 me-1" /> Block</>}
                          </Button>
                          {!tag.business_id ? (
                            <Button size="sm" variant="default" onClick={() => openAssign(tag.id)}>
                              <UserPlus className="w-3 h-3 me-1" /> Assign
                            </Button>
                          ) : (
                            <>
                              <Button size="sm" variant="outline" onClick={() => openAssign(tag.id)}>
                                <RefreshCw className="w-3 h-3 me-1" /> Reassign
                              </Button>
                              <Button size="sm" variant="outline" onClick={() => unassign(tag)}>
                                <Link2Off className="w-3 h-3 me-1" /> Unassign
                              </Button>
                            </>
                          )}
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          )}
        </TabsContent>
      </Tabs>

      {bulkOpen && (
        <Card className="border-primary">
          <CardContent className="p-4 space-y-3">
            <h3 className="font-semibold">Bulk Pre-generate Tag Codes</h3>
            <p className="text-xs text-muted-foreground">
              Generates unassigned tag codes for printing. Assign them to businesses later.
            </p>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-xs">Count (max 100)</label>
                <Input type="number" min={1} max={100} value={bulkCount}
                  onChange={e => setBulkCount(parseInt(e.target.value) || 0)} />
              </div>
              <div>
                <label className="text-xs">Label prefix</label>
                <Input value={bulkLabel} onChange={e => setBulkLabel(e.target.value)} />
              </div>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" onClick={() => setBulkOpen(false)}>Cancel</Button>
              <Button onClick={bulkGenerate}>Generate</Button>
            </div>
          </CardContent>
        </Card>
      )}

      <AdminAssignNFCModal
        open={assignOpen}
        onOpenChange={setAssignOpen}
        mode={assignMode}
        tagId={assignTagId}
        onDone={fetchData}
      />
    </div>
  );
}
